### ISSUE TITLE
Can't Log In with Two Step Verification

### ISSUE THREAD

**Issue by speedyflipper** [cyberjunky/home-assistant-garmin_connect#69]
When two step verification is enabled, there is no prompt for the OTP. 

023-02-20 02:07:28.722 ERROR (MainThread) [custom_components.garmin_connect] Error occurred during Garmin Connect login request: Authentication error
2023-02-20 02:07:28.722 ERROR (MainThread) [custom_components.garmin_connect] Error fetching garmin_connect data: Authentication error

**Comment by cyberjunky** [comment]
Known issue, I have information on how to implement MFA support, but have to find some time to implement it.

**Comment by acidkill** [comment]
I have the same issue. Noticed as only “unavailable” as states and no mfa implementation caused spamming my mailbox

**Comment by ArnyminerZ** [comment]
+1 for this. If you have some information @cyberjunky maybe you can post it in this issue, and I can try to help a bit

**Comment by plaiddk** [comment]
+1 on this issue

**Comment by m2726** [comment]
+1 for this.

**Comment by GalKar83** [comment]
First of all thanks a lot for your hard work.
I can't understand from the description if the integration will support  MFA eventually or not.
Apparently for me, I can't disable the MFA function as it was set for permanent two-step verification.
I'm trying to contact Garmin in order to solve this but I think it would be the best if the integration will support this function anyway.
Can you please confirm if this is something that is under development?

**Comment by cyberjunky** [comment]
Closed because added to parent ticket https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117
